### ISSUE TITLE
Input files required

### ISSUE THREAD

**Issue by Ashutosh-Londhe** [Rtoax/2D3D-TI-FD-RTM-cuda#1]
Can you please share inputs files mentioned in your code. Please share repository from where i can download these files

**Comment by Rtoax** [comment]
i m so sorry that im  not working on  geoscience anymore. and i dont have any input data left on my xomputer.  you  can get the input data with C
FILE *fp = fopen(..., "wb")
fwrite(..., ..., ..., fp)

**Comment by Rtoax** [comment]
i m so sorry that im  not working on  geoscience anymore. and i dont have any input data left on my xomputer.  you  can get the input data with C
FILE *fp = fopen(..., "wb")
fwrite(..., ..., ..., fp)

i m so sorry that im  not working on  geoscience anymore. and i dont have any input data left on my xomputer.  you  can get the input data with C
FILE *fp = fopen(..., "wb")
fwrite(..., ..., ..., fp)

**Comment by Rtoax** [comment]
maybe there is a method you can get my code's input data format, for example download a .su(seismic unix data format). and do this
sustrip  <input.su  >output.bin
then, the output.dat is the right format for my code.
i helped?

**Comment by Ashutosh-Londhe** [comment]
No issues.
Thanks for your help. 
I am aware of SU package so that will not be the problem.  


Just one more question, the thrust model u mentioned is it synthetic or real field.

**Comment by Rtoax** [comment]
of course is not real field😭 , the S/N is too high😂 
im so sorry that my english is not good.🤔

**Comment by Ashutosh-Londhe** [comment]
Ok thanks for ur help

**Comment by lilux618** [comment]
> Ok thanks for ur help



> No issues. Thanks for your help. I am aware of SU package so that will not be the problem.
> 
> Just one more question, the thrust model u mentioned is it synthetic or real field.

Hello , would you like to share the input file ? I am not  familar with that

**Comment by Rtoax** [comment]
> > Ok thanks for ur help
> 
> > No issues. Thanks for your help. I am aware of SU package so that will not be the problem.
> > Just one more question, the thrust model u mentioned is it synthetic or real field.
> 
> Hello , would you like to share the input file ? I am not familar with that

Sorry, I don't have it.
